
** About
Neural network simulator developed by Felix Hoffmann for his PhD.
Original at https://github.com/synsrv/src_net.

Network simulation using Brian 2 and Pypet written to analyse the survivability of transient synapses of cortical neurons.

** Requirements
To run the network simulation a Python 3 environment with Brian 2, and Pypet is required. Git also has to be installed.

Any recent version of [[https://github.com/brian-team/brian2][Brian 2]] should work.
However, to run very long simulations a fix discussed in [[https://github.com/brian-team/brian2/pull/1057][#1057]] is required.

Below is an example installation routine for setting up a virtualenv (tested on Ubuntu 16.04 only).

If you see issues with long running simulations, a patch to brian2 needs to be applied.
You can try to install an old version of brian2 with the patch:
#+BEGIN_SRC sh
# Brian 2 branch that fixes bug for long simulations https://github.com/brian-team/brian2/pull/1057
pip uninstall brian2
pip install -e git+https://github.com/brian-team/brian2@355cbf98061f2ae4c4afdc1600f363c5d8c0979d#egg=Brian2
#+END_SRC

If that doesn't work, the patch likely needs to be rebased on an up-to-date brian2, see #4.

#+BEGIN_SRC sh
#!/bin/sh

virtualenv -p python3 /home/$USER/env/synsrv
source /home/$USER/env/synsrv/bin/activate

pip install -r requirements.txt
#+END_SRC


** Installation

Get the code from this repository including submodules with

: git clone  --recurse-submodules https://github.com/excinhbal/network

It is highly recommended to limit the level of parallelization when building the standalone_cpp simulator.
In ~$HOME/.brian/user_preferences~ write, where ~4~ is the number of CPU cores your PC has:
#+BEGIN_SRC ini
[devices.cpp_standalone]
extra_make_args_unix = ["-j4"]
#+END_SRC

** Run a simulation
To verify your installation, within ~src_net~ run

#+BEGIN_SRC sh
./run_test.sh -l tests/net_tests/test_standard_net/
#+END_SRC

This will create a directory ~tests/~ on the same level as ~src_net~ where the code is copied an executed.

** Explore parameters

To run simulations exploring different parameter sets, create an ~explored_params.py~ in ~src_net/net/~, as for example found in any of the tests in ~net_tests/~. In the ~input_dict~ of ~explored_params.py~ specify the parameter setting of your choice and the runn simulation via

#+BEGIN_SRC 
./run.sh -l -n 2 -P "_two-concurrent-sims" -E
#+END_SRC

This will create ~running/~ and ~completed/~ directories on the same level as ~src_net/~. Once finished, the simulation directory is moved from ~running/~ to ~completed/~.

** Run tests

There are multiple sets of tests currently, they fall in two broad categories:
1. tests that can be run with ~pytest~: ~pytest tests/pytests~
2. all other tests, which can be run using ~./run_tests.sh~ as shown above


